# Generated by Django 4.0.6 on 2025-01-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0003_alter_reporte_promedio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='calificaciones',
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Control.estudiante'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='Control.calificacion'),
        ),
    ]
