# Generated by Django 4.0.6 on 2025-01-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0006_alter_reporte_estado_alter_reporte_promedio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reporte',
            unique_together={('estudiante', 'clase')},
        ),
    ]
